apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener-lauren
  name: cnkt-event-listener-lauren
spec:
  serviceAccountName: pipeline-lauren
  triggers:
  - name: lauren-demo
    interceptors:
    - ref:
        name: "cel"
      params:
      - name: "filter"
        value: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master' && body.repository.full_name == 'client-engineering-gitops-htz/lauren-demo'
    bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding-lauren
    template:
      ref: lauren-demo