apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgBgLQq9aNpJ61Prdz2ok/mh+gDY6QYXkMRLo57XuzUilZK5M2tvvIYXeAwmSc1gzV5aVVMDA3vFN4vvEjTPA2l3hcGbjCi1zlhsxeF84Mpw1vw/KeD+Nowkt9WH0KQFYE0CFnF71c4DLCYNjNdqIM3HUgkJthszxMYgsVGUjHk+07AwdFsvPcECr1mUfl6bWXYpVMDTlNpCULrfTeBmHoPaQ7GgJhtXs3urVOvMuFD08bqg3eVHsLcqz8WptOfdVwEyN6JE7qg7MF29J49h2Csc9CK9yZ7p+zI5i7e4OubGhvbwXBrZy72w71+Lcef5op5eRXfYkQ8zx2+wVg6r5mAf/E7JvnPUX3WhlYMWZuZEQL6i5PL0F5SeUwkFyPQPTgaeBIZrK57ZdT+9PjfCJNeStKjgfnpCiM9AyecziXV9PRp+P2eJa/Szs2nw7T8KY6kcm9UCAhAoqSRPMfnQudU7HTFY56gXifdhUq5wJOL+udFV/Emv/8sCru2LKeEwxfXUyLb1OMywsHVV+gvOH4rwmNAn1k2bhsvfMOnqmjN5CBz8pJKRJsOpHcH7tAuEmWH01HQT/lHiOpSVuRwr12cCvpfvyjZ5kK4mw7XzY1PztRYvdtf5AQy7Bbi19K10zaSazPmRG2xqYUK7d5RDoCEdv9d5haY3Zpld9Bzxvi3BQjj0IdWBPCTDfpHe68jGmBR3fq6VcztNiplSXNa9sO2OxhV5OtzFjAAnurfaVU0hWAkn2mVic4Lq
    username: AgDbRHvOE5w4BmoI44luGDhvI8vy1RbeJQIwyppXTir5/gENag+m/sFec+cgqTVPxt15lqzubZab4iQfWhutAMMeI/7Wfh9C5oLdzwDvztJDjCHUxR95h4CcI7097JI4aY4H0e532+VGjJRwOh7+cjvgYyc/0rmv6C0KiS8MM+bwmdsuIJoaUS9mr4e8mtd5Kqu03w4RqRy4vaeOShwqMbsl/XbdLjK+17EjgJUROjfGP76urMhAtI/LQ1HZuNl3nWJGAa728AfAcCiG1WWHgKidjb9RWTUc1QXsq3ZFgZAgVP3MiyRnh4H9b400axmgDO+unsKAA5PaA4awK0sH0GzrSuVs62SGtjMzm3pn/b5J8yDlANSWzcFpcYk3OlajIU7i6cQQqa010LP14SFLGHMgH4yGbU7+zzi5jx+Vf0hW3lHsvECYKLoQGRmCLVt/XeW68tnTixbDo1u61F+kISNWjWQ1HTnD0xJbYE7b4SA9Uwaj/2JR526wldKysYv7Ge1r6NBMCmxZtAKAV0P7wFDSSeI7p9FMw8jnWL4rBn0mt3qAv5QSKq0AAFLY6B3LmqHsWHh/jx7p4azTv9QdpXQ2YYJGHibuxiSDTRK0USRCzKzH4iFMn0W8YfwenwwUKlHDw7j/gIoqV2MbjGEdnv718en9Qga/tKwk1YOPYT2USjAyAk/f5v8SqHUNKK7KA2WHdOtiTZBS
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

