resources:
- configmaps/gitops-repo-configmap.yaml
- eventlisteners/cntk-event-listener.yaml
- pipelines/ibm-lauren-dev-stage.yaml
- pipelines/lauren-demo-dev.yaml
- roles/custom-ci-pipeline-sa-rolebinding.yaml
- roles/custom-dev-pipeline-sa-rolebinding.yaml
- routes/cntk-route.yaml
- secrets/artifactory-access-secret.yaml
- secrets/git-credentials-secret.yaml
- secrets/ibm-entitled-registry-credentials-secret.yaml
- tasks/1-java-maven-test.yaml
- tasks/2-lint-dockerfile.yaml
- tasks/4-deploy.yaml
- tasks/4-smoke-test.yaml
- tasks/5-health-check.yaml
- tasks/10-gitops.yaml
- tasks/ibm-build-tag-push.yaml
- tasks/ibm-functional-test.yaml
- tasks/ibm-helm-release.yaml
- tasks/ibm-img-release.yaml
- tasks/ibm-img-scan.yaml
- tasks/ibm-setup.yaml
- tasks/ibm-tag-release.yaml
- triggerbindings/cntk-binding.yaml
- triggertemplates/lauren-demo-dev.yaml
