dependencies:
<<<<<<< HEAD
  - name: lauren-demo-dev
    version: 0.0.5
=======
  - name: lauren-demo
    version: 0.0.6
>>>>>>> 0105318f81089f99e00e9beed5c597c37f95c49f
    repository: http://artifactory-artifactory.tools:8082/artifactory/generic-local/ci
